# Generated by Django 3.2.9 on 2022-09-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('design', models.CharField(choices=[('SDE', 'Software Developer'), ('DA', 'Data Analyst'), ('ST', 'Software Tester')], max_length=20)),
                ('sal', models.IntegerField()),
                ('age', models.IntegerField(null=True)),
                ('pos', models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin')], max_length=15)),
                ('pswd', models.IntegerField()),
            ],
        ),
    ]
